In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\91798\anaconda3\lib\site-packages (9.5.0)

In [2]:
import mysql.connector
import pandas as pd
connection = mysql.connector.connect(
    host="Hidden for security purposes",
    user="Hidden for security purposes",
    password=r"Hidden for security purposes", 
    database="Hidden for security purposes",
    auth_plugin="mysql_native_password"
)

cursor = connection.cursor()

In [3]:
def run_query(query):
    cursor.execute(query)
    rows = cursor.fetchall()
    cols = [i[0] for i in cursor.description]
    return pd.DataFrame(rows, columns=cols)

In [4]:
#a) Can you get all data about movies?
run_query("SELECT * FROM movies;")

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,"Pirates of the Caribbean: At World""s End",300000000,139,2007-05-19,961000000,"Pirates of the Caribbean: At World""s End",6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bonds past sends him on...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766
5,43602,Spider-Man 3,258000000,115,2007-05-01,890871626,Spider-Man 3,5.9,3576,The seemingly invincible Spider-Man goes up ag...,The battle within.,559,4767
6,43603,Tangled,260000000,48,2010-11-24,591794936,Tangled,7.4,3330,"When the kingdom""s most wanted-and most charmi...",They're taking adventure to new lengths.,38757,4768
7,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769
8,43605,Harry Potter and the Half-Blood Prince,250000000,98,2009-07-07,933959197,Harry Potter and the Half-Blood Prince,7.4,5293,"As Harry begins his sixth year at Hogwarts, he...",Dark Secrets Revealed,767,4770
9,43607,Superman Returns,270000000,57,2006-06-28,391081192,Superman Returns,5.4,1400,Superman returns to discover his 5-year absenc...,None,1452,4772
10,43608,Quantum of Solace,200000000,107,2008-10-30,586090727,Quantum of Solace,6.1,2965,Quantum of Solace continues the adventures of ...,"For love, for hate, for justice, for revenge.",10764,4773
11,43609,"Pirates of the Caribbean: Dead Man""s Chest",200000000,145,2006-06-20,1065659812,"Pirates of the Caribbean: Dead Man""s Chest",7.0,5246,Captain Jack Sparrow works his way out of a bl...,Jack is back!,58,4763
12,43610,The Lone Ranger,255000000,49,2013-07-03,89289910,The Lone Ranger,5.9,2311,The Texas Rangers chase down a gang of outlaws...,Never Take Off the Mask,57201,4763
13,43611,Man of Steel,225000000,99,2013-06-12,662845518,Man of Steel,6.5,6359,A young boy learns that he has extraordinary p...,You will believe that a man can fly.,49521,4771
14,43612,The Chronicles of Narnia: Prince Caspian,225000000,53,2008-05-15,419651413,The Chronicles of Narnia: Prince Caspian,6.3,1630,One year after their incredible adventures in ...,Hope has a new face.,2454,4774
15,43613,The Avengers,220000000,144,2012-04-25,1519557910,The Avengers,7.4,11776,When an unexpected enemy emerges and threatens...,Some assembly required.,24428,4769
16,43614,Pirates of the Caribbean: On Stranger Tides,380000000,135,2011-05-14,1045713802,Pirates of the Caribbean: On Stranger Tides,6.4,4948,Captain Jack Sparrow crosses paths with a woma...,Live Forever Or Die Trying.,1865,4775
17,43615,Men in Black 3,225000000,52,2012-05-23,624026776,Men in Black 3,6.2,4160,Agents J (Will Smith) and K (Tommy Lee Jones) ...,They are back... in time.,41154,4776
18,43616,The Hobbit: The Battle of the Five Armies,250000000,120,2014-12-10,956019788,The Hobbit: The Battle of the Five Armies,7.1,4760,Immediately after the events of The Desolation...,Witness the defining chapter of the Middle-Ear...,122917,4777
19,43617,The Amazing Spider-Man,215000000,89,2012-06-27,752215857,The Amazing Spider-Man,6.5,6586,Peter Parker is an outcast high schooler aband...,The untold story begins.,1930,4778
20,43618,Robin Hood,200000000,37,2010-05-12,310669540,Robin Hood,6.2,1398,When soldier Robin happens upon the dying Robe...,"Rise and rise again, until lambs become lions.",20662,4779
21,43619,The Hobbit: The Desolation of Smaug,250000000,94,2013-12-11,958400000,The Hobbit: The Desolation of Smaug,7.6,4524,"The Dwarves, Bilbo and Gandalf have successful...",Beyond darkness... beyond desolation... lies t...,57158,4777
22,43620,The Golden Compass,180000000,42,2007-12-04,372234864,The Golden Compass,5.8,1303,"After overhearing a shocking secret, precociou...",There are worlds beyond our own - the compass ...,2268,4780
23,43621,King Kong,207000000,61,2005-12-14,550000000,King Kong,6.6,2337,"In 1933 New York, an overly ambitious movie pr...",The eighth wonder of the world.,254,4777
24,43622,Titanic,200000000,100,1997-11-18,1845034188,Titanic,7.5,7562,"84 years later, a 101-year-old woman named Ros...",Nothing on Earth could come between them.,597,4762
25,43623,Captain America: Civil War,250000000,198,2016-04-27,1153304495,Captain America: Civil War,7.1,7241,"Following the events of Age of Ultron, the col...",Divided We Fall,271110,4781
26,43624,Battleship,209000000,64,2012-04-11,303025485,Battleship,5.5,2114,"When mankind beams a radio signal into space, ...",The Battle for Earth Begins at Sea,44833,4782
27,43625,Jurassic World,150000000,418,2015-06-09,1513528810,Jurassic World,6.5,8662,Twenty-two years after the events of Jurassic ...,The park is open.,135397,4783
28,43626,Skyfall,200000000,93,2012-10-25,1108561013,Skyfall,6.9,7604,"When Bond""s latest assignment goes gravely wro...",Think on your sins.,37724,4764
29,43627,Spider-Man 2,200000000,35,2004-06-25,783766341,Spider-Man 2,6.7,4321,Peter Parker is going through a major identity...,"There""s a hero in all of us.",558,4767
30,43628,Iron Man 3,200000000,77,2013-04-18,1215439994,Iron Man 3,6.8,8806,"When Tony Stark""s world is torn apart by a for...",Unleash the power behind the armor.,68721,4784
31,43629,Alice in Wonderland,200000000,78,2010-03-03,1025491110,Alice in Wonderland,6.4,4645,"Alice, an unpretentious and individual 19-year...",You're invited to a very important date.,12155,4785
32,43630,X-Men: The Last Stand,210000000,3,2006-05-24,459359555,X-Men: The Last Stand,6.3,3525,"When a cure is found to treat mutations, lines...",Take a Stand,36668,4786
33,43631,Monsters University,200000000,89,2013-06-20,743559607,Monsters University,7.0,3528,A look at the relationship between Mike and Su...,School never looked this scary.,62211,4787
34,43632,Transformers: Revenge of the Fallen,150000000,21,2009-06-19,836297228,Transformers: Revenge of the Fallen,6.0,3138,Sam Witwicky leaves the Autobots behind for a ...,Revenge is coming.,8373,4788
35,43633,Transformers: Age of Extinction,210000000,116,2014-06-25,1091405097,Transformers: Age of Extinction,5.8,3095,"As humanity picks up the pieces, following the...","This is not war. It""s extinction.",91314,4788
36,43634,Oz: The Great and Powerful,200000000,46,2013-03-07,491868548,Oz: The Great and Powerful,5.7,3530,"Oscar Diggs, a small-time circus illusionist a...","In Oz, nothing is what it seems",68728,4767
37,43636,TRON: Legacy,170000000,73,2010-12-10,400062763,TRON: Legacy,6.3,2841,"Sam Flynn, the tech-savvy and daring son of Ke...",The Game Has Changed.,20526,4789
38,43637,Cars 2,200000000,49,2011-06-11,559852396,Cars 2,5.8,2033,Star race car Lightning McQueen and his pal Ma...,Ka-ciao!,49013,4790
39,43638,Green Lantern,200000000,51,2011-06-16,219851172,Green Lantern,5.1,2487,"For centuries, a small but powerful force of w...","In our darkest hour, there will be light.",44912,4791
40,43639,Toy Story 3,200000000,59,2010-06-16,1066969703,Toy Story 3,7.6,4597,"Woody, Buzz, and the rest of Andy""s toys haven...",No toy gets left behind.,10193,4792
41,43640,Terminator Salvation,200000000,71,2009-05-20,371353001,Terminator Salvation,5.9,2463,"All grown up in post-apocalyptic 2018, John Co...",The End Begins.,534,4793
42,43641,Furious 7,190000000,102,2015-04-01,1506249360,Furious 7,7.3,4176,Deckard Shaw seeks revenge against Dominic Tor...,Vengeance Hits Home,168259,4794
43,43642,World War Z,200000000,81,2013-06-20,531865000,World War Z,6.7,5560,Life for former United Nations investigator Ge...,Remember Philly!,72190,4773
44,43644,Star Trek Into Darkness,190000000,78,2013-05-05,467365246,Star Trek Into Darkness,7.4,4418,When the crew of the Enterprise is called back...,Earth Will Fall,54138,4795
45,43646,The Great Gatsby,105000000,61,2013-05-10,351040419,The Great Gatsby,7.3,3769,"An adaptation of F. Scott Fitzgerald""s Long Is...",Reserving judgments is a matter of infinite ho...,64682,4796
46,43647,Prince of Persia: The Sands of Time,150000000,62,2010-05-19,335154643,Prince of Persia: The Sands of Time,6.2,2317,A rogue prince reluctantly joins forces with a...,Defy the Future,9543,4797

In [5]:
#b) How do you get all data about directors?
run_query("SELECT * FROM directors;")

                   name    id  gender      uid department
0         James Cameron  4762       2     2710  Directing
1        Gore Verbinski  4763       2     1704  Directing
2            Sam Mendes  4764       2       39  Directing
3     Christopher Nolan  4765       2      525  Directing
4        Andrew Stanton  4766       2        7  Directing
...                 ...   ...     ...      ...        ...
2344      Shane Carruth  7106       2    76624  Directing
2345   Neill Dela Llana  7107       0  1174437  Directing
2346        Scott Smith  7108       0  1219158  Directing
2347        Daniel Hsia  7109       2   208138  Directing
2348   Brian Herzlinger  7110       2    85563  Directing

[2349 rows x 5 columns]

In [6]:
#c) Check how many movies are present in IMDB.
run_query("SELECT COUNT(*) AS total_movies FROM movies;")

   total_movies
0            47

In [7]:
#d) Find these 3 directors: James Cameron ; Luc Besson ; John Woo
run_query("select name from directors where name IN('James Cameron','Luc Besson','John Woo');")

            name
0  James Cameron
1       John Woo
2     Luc Besson

In [8]:
#e) Find all directors with name starting with S.
run_query("select name from directors where name LIKE 's%';")

                 name
0          Sam Mendes
1           Sam Raimi
2         Shane Black
3    Steven Spielberg
4     Stephen Sommers
..                ...
168       Sai Varadan
169  Stephen Langford
170        Sut Jhally
171     Shane Carruth
172       Scott Smith

[173 rows x 1 columns]

In [9]:
#f) Count female directors.
run_query("select count(*) from directors where gender='1';")

   count(*)
0       150

In [10]:
#g) Find the name of the 10th first women directors?
run_query("SELECT name FROM directors WHERE gender = 1 ORDER BY name LIMIT 1 OFFSET 9;")

               name
0  Amy Holden Jones

In [17]:
#h) What are the 3 most popular movies?
run_query("SELECT title FROM movies ORDER BY popularity DESC LIMIT 3;")

                        title
0              Jurassic World
1  Captain America: Civil War
2                      Avatar

In [12]:
#i) What are the 3 most bankable movies?
run_query("SELECT title,revenue FROM movies ORDER BY revenue DESC LIMIT 3;")

          title     revenue
0        Avatar  2787965087
1       Titanic  1845034188
2  The Avengers  1519557910

In [13]:
#j) What is the most awarded average vote since the January 1st, 2000?
run_query("SELECT title,vote_average FROM movies WHERE release_date >= '2000-01-01' ORDER BY vote_average DESC LIMIT 1;")

                   title  vote_average
0  The Dark Knight Rises           7.6

In [19]:
#k) Which movie(s) were directed by Brenda Chapman?
run_query("SELECT m.title FROM movies m JOIN directors d ON m.uid = d.uid WHERE d.name = 'Brenda Chapman';")
#Brenda Chapman’s ID and UID exists in the directors table, but it does not appear in the movies table, so no movies are assigned to her.

Empty DataFrame
Columns: [title]
Index: []

In [15]:
#l) Which director made the most movies?
run_query("SELECT d.name AS director_name,COUNT(m.id) AS total_movies,GROUP_CONCAT(m.title SEPARATOR ', ') AS movie_list FROM directors d JOIN movies m ON d.id = m.director_id GROUP BY d.id, d.name ORDER BY total_movies DESC LIMIT 1;")

,director_name,total_movies,movie_list
0,Gore Verbinski,3,"Pirates of the Caribbean: At World""s End, Pira..."

In [16]:
#m) Which director is the most bankable?
run_query("SELECT d.name, SUM(m.revenue) AS total_revenue FROM directors d JOIN movies m ON d.id = m.director_id GROUP BY d.name ORDER BY total_revenue DESC LIMIT 1;")

            name total_revenue
0  James Cameron    4632999275